DEVICE_NAME = "my_device"

DEVICE_ADDRESS = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"

autoconnect = true

[[services.battery]]
NAME = "battery service"
UUID = "180f"

[[services.battery.characteristics.level]]
NAME = "level"
UUID = "2a19"

[[commands]]
read_battery = ["read", "battery service", "level"]
sub_battery = ["notify", "battery service", "level"]
