DEVICE_NAME = "my_device"

DEVICE_ADDRESS = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"

[[services.color]]
NAME = "color service"
UUID = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"

[[services.color.characteristics.rgb]]
NAME = "rgb"
UUID = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"

[[commands]]
led_red = ["write", "color service", "rgb", 0xff, 0x00, 0x00]
led_green = ["write", "color service", "rgb", 0x00, 0xff, 0x00]
led_blue = ["write", "color service", "rgb", 0x00, 0x00, 0xff]
get_color = ["read", "color service", "rgb"]
