DEVICE_NAME = "my_device"

DEVICE_ADDRESS = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"

[[services.hrs]]
NAME = "Heart rate services"
UUID = "180d"

[[services.hrs.characteristics.mesurement]]
NAME = "Heart rate mesurement"
UUID = "2a37"

[[services.hrs.characteristics.location]]
NAME = "Body sensor location"
UUID = "2a38"

[[commands]]
get_location = ["read", "Heart rate services", "Body sensor location"]
get_rate = ["read", "Heart rate services", "Heart rate mesurement"]
