DEVICE_NAME = "my_device"

DEVICE_ADDRESS = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"

[[services.nus]]
NAME = "Nordic UART Service"
UUID = "6E400001-B5A3-F393-E0A9-E50E24DCCA9E"

[[services.nus.characteristics.tx]]
NAME = "tx"
UUID = "6E400003-B5A3-F393-E0A9-E50E24DCCA9E"
PERMS = ["write"]

[[services.nus.characteristics.rx]]
NAME = "rx"
UUID = "6E400002-B5A3-F393-E0A9-E50E24DCCA9E"
PERMS = ["read", "notify"]
